//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWcfService.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class intranet2013Entities : DbContext
    {
        public intranet2013Entities()
            : base("name=intranet2013Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EkDosya> EkDosyas { get; set; }
        public virtual DbSet<Haber> Habers { get; set; }
        public virtual DbSet<sozluk_HaberTurleri> sozluk_HaberTurleri { get; set; }
        public virtual DbSet<sozluk_Baskanliklar> sozluk_Baskanliklar { get; set; }
        public virtual DbSet<sozluk_Birimler> sozluk_Birimler { get; set; }
    }
}
