//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWcfService.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkDosya
    {
        public int No { get; set; }
        public Nullable<int> HaberNo { get; set; }
        public string Ad { get; set; }
        public string Boyut { get; set; }
        public string Adres { get; set; }
        public string Tur { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Onay { get; set; }
    }
}
