//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWcfService.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haber
    {
        public int No { get; set; }
        public Nullable<int> Tur { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public Nullable<bool> EkDosyaVarMi { get; set; }
        public Nullable<bool> FotoGaleriMi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<int> YayinSuresi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string GonderenAdi { get; set; }
        public string GonderenSoyadi { get; set; }
        public Nullable<int> GonderenSicil { get; set; }
        public string GonderenBirim { get; set; }
        public string GonderenBaskanlik { get; set; }
        public string GonderenEposta { get; set; }
        public string GonderenTelefon { get; set; }
        public Nullable<int> OnemDerecesi { get; set; }
        public string Onaylayan { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public Nullable<int> OnayDurumu { get; set; }
        public string OnayGerekcesi { get; set; }
        public string YayınYeri { get; set; }
    }
}
