//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWcfService.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sozluk_Baskanliklar
    {
        public int Id { get; set; }
        public string BaskanlikAdi { get; set; }
        public Nullable<int> OnemDerecesi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> BolgeId { get; set; }
    }
}
